title: Testing the template in docs folder
description: A starter template for a Jeykll site using the Just the Docs theme! A starter template for a Jeykll site using the Just the Docs theme! A starter template for a Jeykll site using the Just the Docs theme! A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://jb-smoker.github.io/jtd
